# Generated by Django 4.2.1 on 2023-05-27 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_employee_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snack',
            fields=[
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('t_name', models.CharField(max_length=30)),
                ('n_value', models.IntegerField(default=0)),
                ('q_available', models.IntegerField(default=0)),
                ('fk_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.client')),
            ],
        ),
    ]
