# Generated by Django 4.1.7 on 2023-03-21 14:15

import apps.user.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.user.managers.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.TextField(choices=[(1, 'Administrador'), (2, 'Vendedor'), (3, 'Cliente')], null=True, verbose_name='rol'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.DecimalField(decimal_places=0, max_digits=20, null=True),
        ),
    ]
