# Generated by Django 4.2.1 on 2023-05-27 17:59

import apps.user.managers
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_options_alter_user_managers_user_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('pk_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Identificador empleado')),
                ('n_salary', models.DecimalField(decimal_places=4, max_digits=10)),
                ('d_start_date_contract', models.DateTimeField()),
                ('d_end_date_contract', models.DateTimeField()),
                ('b_is_active', models.BooleanField(default=True)),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('user.user',),
            managers=[
                ('objects', apps.user.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('pk_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Identificador cliente')),
                ('n_points', models.DecimalField(decimal_places=1, max_digits=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('user.user',),
            managers=[
                ('objects', apps.user.managers.UserManager()),
            ],
        ),
    ]
