# Generated by Django 4.2.1 on 2023-05-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unity',
            fields=[
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('t_name', models.CharField(max_length=30)),
                ('t_location', models.CharField(max_length=30)),
            ],
        ),
    ]
