# Generated by Django 4.2.1 on 2023-05-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('b_adult', models.BooleanField(default=False, verbose_name='Adultos')),
                ('t_actors', models.CharField(blank='', max_length=30, verbose_name='Actores')),
                ('t_overview', models.CharField(blank='', max_length=30, verbose_name='Sinopsis')),
                ('t_title', models.CharField(blank='', max_length=30, verbose_name='Titulo')),
                ('n_rating', models.IntegerField(verbose_name='Calificacion')),
                ('t_genre', models.CharField(blank='No aplica', max_length=30, verbose_name='Genero')),
            ],
        ),
    ]
