# Generated by Django 4.2.1 on 2023-05-27 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_employee_client'),
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('t_type', models.CharField(max_length=30)),
                ('t_status', models.CharField(max_length=12)),
                ('fk_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.client')),
                ('fk_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.show', verbose_name='')),
            ],
        ),
    ]
