# Generated by Django 4.2.1 on 2023-05-27 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('d_time', models.DateTimeField()),
                ('fk_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movies', verbose_name='Llave primaria películas')),
            ],
        ),
    ]
